#permet les modifications dynamiques sur notre container

version: '3'

services:
  web: 
    build: .
    container_name: machine_learning
    #ce qui va s'éxecuter quand je vais lancer la commande
    command : uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000

    #assure le dynamisme 
    volumes:
      - .:/app

