FROM python:3.13-slim

#definit un repertoire de travail dans le contener 

WORKDIR /app

#copier le ficher resuirements dans le conteneur

COPY requirements.txt /app/
#installer les dépendances

RUN pip install -r requirements.txt 

#copier le contenu de mon réportoire / projet dans le conteneur 
COPY . /app 

#excuter  l'application fast API sur docker

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

